function nbt_lowpass_playground_irka
% NBT-like playground + 4n-order fit + IRKA reduction to 2n
%
% Flow:
%   1) Define analog prototype H_target(s)
%   2) Build experimental Möbius/NBT-like digital target on frequency grid
%   3) Fit a 4n-order digital IIR to that target response
%   4) Reduce the fitted 4n-order IIR to 2n-order with discrete IRKA
%   5) Compare:
%        - analog prototype
%        - naive BLT
%        - direct Möbius target
%        - fitted 4n-order IIR
%        - IRKA reduced 2n-order IIR
%
% Notes:
% - This is NOT the exact 2022 NBT algorithm.
% - The "4n-order digital system" here is obtained by fitting the
%   frequency response generated by the experimental remap.
% - IRKA acts on that fitted 4n-order system.

    close all; clc;

    %% ---------------- Default parameters ----------------
    P.fs            = 48000;     % sampling rate [Hz]
    P.fc            = 4000;      % analog LP cutoff [Hz]
    P.Q             = 0.707;     % analog LP Q
    P.fo_ratio      = 1.0;       % Omega_o / (pi*fs)
    P.fcmap_ratio   = 1.0;       % Omega_c / (pi*fs)
    P.gammaHat      = 2.058;     % gamma / Omega_o^2
    P.branch        = -1;        % lower by default

    % fitting / reduction defaults
    P.fitDenseN     = 4096;      % digital frequency samples
    P.fitMaxIter    = 30;        % invfreqz max iterations
    P.irkaMaxIter   = 50;
    P.irkaTol       = 1e-8;

    %% ---------------- Figure & axes ----------------
    fig = figure( ...
        'Name', 'NBT-like Playground + IRKA', ...
        'NumberTitle', 'off', ...
        'Color', 'w', ...
        'Position', [40 40 1500 860]);

    ax1 = axes('Parent', fig, 'Position', [0.07 0.56 0.63 0.38]); % analog
    ax2 = axes('Parent', fig, 'Position', [0.07 0.08 0.63 0.40]); % digital

    infoBox = uicontrol(fig, 'Style', 'text', ...
        'Units', 'normalized', ...
        'Position', [0.73 0.58 0.24 0.33], ...
        'HorizontalAlignment', 'left', ...
        'BackgroundColor', 'w', ...
        'FontName', 'Consolas', ...
        'FontSize', 10);

    %% ---------------- UI ranges ----------------
    fc_min = 50;
    fc_max = min(24000, 0.49 * P.fs);

    q_min = 0.2;
    q_max = 10.0;

    fo_ratio_min = 0.2;
    fo_ratio_max = 2.0;

    fcmap_ratio_min = 0.2;
    fcmap_ratio_max = 1;

    gammaHat_min = 0.2;
    gammaHat_max = 5.0;

    %% ---------------- UI panel ----------------
    uipanel(fig, 'Title', 'Controls', ...
        'FontWeight', 'bold', ...
        'Units', 'normalized', ...
        'Position', [0.73 0.08 0.24 0.46], ...
        'BackgroundColor', 'w');

    y0 = 0.47;
    dy = 0.08;

    % fc (log)
    uicontrol(fig, 'Style', 'text', 'Units', 'normalized', ...
        'Position', [0.75 y0 0.18 0.03], ...
        'String', 'Cutoff fc (Hz, log)', ...
        'BackgroundColor', 'w', 'HorizontalAlignment', 'left');

    s_fc = uicontrol(fig, 'Style', 'slider', 'Units', 'normalized', ...
        'Position', [0.75 y0-0.03 0.18 0.03], ...
        'Min', log10(fc_min), 'Max', log10(fc_max), ...
        'Value', log10(P.fc), ...
        'Callback', @updatePlots);

    t_fc = uicontrol(fig, 'Style', 'edit', 'Units', 'normalized', ...
        'Position', [0.94 y0-0.03 0.03 0.03], ...
        'String', num2str(P.fc, '%.1f'), ...
        'Callback', @editCallback);

    % Q (log)
    y = y0 - dy;
    uicontrol(fig, 'Style', 'text', 'Units', 'normalized', ...
        'Position', [0.75 y 0.18 0.03], ...
        'String', 'Q (log)', ...
        'BackgroundColor', 'w', 'HorizontalAlignment', 'left');

    s_q = uicontrol(fig, 'Style', 'slider', 'Units', 'normalized', ...
        'Position', [0.75 y-0.03 0.18 0.03], ...
        'Min', log10(q_min), 'Max', log10(q_max), ...
        'Value', log10(P.Q), ...
        'Callback', @updatePlots);

    t_q = uicontrol(fig, 'Style', 'edit', 'Units', 'normalized', ...
        'Position', [0.94 y-0.03 0.03 0.03], ...
        'String', num2str(P.Q, '%.3f'), ...
        'Callback', @editCallback);

    % fo ratio
    y = y0 - 2*dy;
    uicontrol(fig, 'Style', 'text', 'Units', 'normalized', ...
        'Position', [0.75 y 0.18 0.03], ...
        'String', 'Omega_o / (pi fs)', ...
        'BackgroundColor', 'w', 'HorizontalAlignment', 'left');

    s_fo = uicontrol(fig, 'Style', 'slider', 'Units', 'normalized', ...
        'Position', [0.75 y-0.03 0.18 0.03], ...
        'Min', fo_ratio_min, 'Max', fo_ratio_max, ...
        'Value', P.fo_ratio, ...
        'Callback', @updatePlots);

    t_fo = uicontrol(fig, 'Style', 'edit', 'Units', 'normalized', ...
        'Position', [0.94 y-0.03 0.03 0.03], ...
        'String', num2str(P.fo_ratio, '%.3f'), ...
        'Callback', @editCallback);

    % fcmap ratio
    y = y0 - 3*dy;
    uicontrol(fig, 'Style', 'text', 'Units', 'normalized', ...
        'Position', [0.75 y 0.18 0.03], ...
        'String', 'Omega_c / (pi fs)', ...
        'BackgroundColor', 'w', 'HorizontalAlignment', 'left');

    s_fcmap = uicontrol(fig, 'Style', 'slider', 'Units', 'normalized', ...
        'Position', [0.75 y-0.03 0.18 0.03], ...
        'Min', fcmap_ratio_min, 'Max', fcmap_ratio_max, ...
        'Value', P.fcmap_ratio, ...
        'Callback', @updatePlots);

    t_fcmap = uicontrol(fig, 'Style', 'edit', 'Units', 'normalized', ...
        'Position', [0.94 y-0.03 0.03 0.03], ...
        'String', num2str(P.fcmap_ratio, '%.3f'), ...
        'Callback', @editCallback);

    % gammaHat
    y = y0 - 4*dy;
    uicontrol(fig, 'Style', 'text', 'Units', 'normalized', ...
        'Position', [0.75 y 0.18 0.03], ...
        'String', 'gammaHat = gamma / Omega_o^2', ...
        'BackgroundColor', 'w', 'HorizontalAlignment', 'left');

    s_gh = uicontrol(fig, 'Style', 'slider', 'Units', 'normalized', ...
        'Position', [0.75 y-0.03 0.18 0.03], ...
        'Min', gammaHat_min, 'Max', gammaHat_max, ...
        'Value', P.gammaHat, ...
        'Callback', @updatePlots);

    t_gh = uicontrol(fig, 'Style', 'edit', 'Units', 'normalized', ...
        'Position', [0.94 y-0.03 0.03 0.03], ...
        'String', num2str(P.gammaHat, '%.3f'), ...
        'Callback', @editCallback);

    % branch selector
    y = y0 - 5*dy;
    uicontrol(fig, 'Style', 'text', 'Units', 'normalized', ...
        'Position', [0.75 y 0.18 0.03], ...
        'String', 'Inverse G2 branch', ...
        'BackgroundColor', 'w', 'HorizontalAlignment', 'left');

    popup_branch = uicontrol(fig, 'Style', 'popupmenu', 'Units', 'normalized', ...
        'Position', [0.75 y-0.03 0.22 0.04], ...
        'String', {'-1 (lower branch)', '+1 (upper branch)'}, ...
        'Value', 1, ...
        'Callback', @updatePlots);

    % reset button
    uicontrol(fig, 'Style', 'pushbutton', 'Units', 'normalized', ...
        'Position', [0.75 0.10 0.22 0.05], ...
        'String', 'Reset Defaults', ...
        'Callback', @resetDefaults);

    updatePlots();

    %% =========================================================
    function resetDefaults(~, ~)
        set(s_fc,    'Value', log10(P.fc));
        set(t_fc,    'String', num2str(P.fc, '%.1f'));

        set(s_q,     'Value', log10(P.Q));
        set(t_q,     'String', num2str(P.Q, '%.3f'));

        set(s_fo,    'Value', P.fo_ratio);
        set(t_fo,    'String', num2str(P.fo_ratio, '%.3f'));

        set(s_fcmap, 'Value', P.fcmap_ratio);
        set(t_fcmap, 'String', num2str(P.fcmap_ratio, '%.3f'));

        set(s_gh,    'Value', P.gammaHat);
        set(t_gh,    'String', num2str(P.gammaHat, '%.3f'));

        set(popup_branch, 'Value', 1);

        updatePlots();
    end

    %% =========================================================
    function editCallback(src, ~)
        val = str2double(get(src, 'String'));
        if isnan(val)
            updatePlots();
            return;
        end

        if src == t_fc
            val = max(fc_min, min(fc_max, val));
            set(s_fc, 'Value', log10(val));
        elseif src == t_q
            val = max(q_min, min(q_max, val));
            set(s_q, 'Value', log10(val));
        elseif src == t_fo
            val = max(fo_ratio_min, min(fo_ratio_max, val));
            set(s_fo, 'Value', val);
        elseif src == t_fcmap
            val = max(fcmap_ratio_min, min(fcmap_ratio_max, val));
            set(s_fcmap, 'Value', val);
        elseif src == t_gh
            val = max(gammaHat_min, min(gammaHat_max, val));
            set(s_gh, 'Value', val);
        end
        updatePlots();
    end

    %% =========================================================
    function updatePlots(~, ~)
        fs_local = P.fs;

        fc_local = 10^(get(s_fc, 'Value'));
        Q_local  = 10^(get(s_q, 'Value'));

        fo_ratio_local    = get(s_fo, 'Value');
        fcmap_ratio_local = get(s_fcmap, 'Value');
        gammaHat_local    = get(s_gh, 'Value');

        branchVal = get(popup_branch, 'Value');
        if branchVal == 1
            branchSign = -1;
        else
            branchSign = +1;
        end

        set(t_fc,    'String', num2str(fc_local, '%.1f'));
        set(t_q,     'String', num2str(Q_local, '%.3f'));
        set(t_fo,    'String', num2str(fo_ratio_local, '%.3f'));
        set(t_fcmap, 'String', num2str(fcmap_ratio_local, '%.3f'));
        set(t_gh,    'String', num2str(gammaHat_local, '%.3f'));

        % ---- analog prototype factory ----
        proto = makePrototype(fc_local, Q_local);
        % proto.Hfun(s), proto.num, proto.den
        nAnalog = max(length(proto.den), length(proto.num)) - 1;

        % target / reduced digital orders
        hiOrder = 4 * nAnalog;
        redOrder = 2 * nAnalog;

        Omega_o = fo_ratio_local * pi * fs_local;
        Omega_c = fcmap_ratio_local * pi * fs_local;
        gamma   = gammaHat_local * Omega_o^2;

        % ---- analog response ----
        N_analog = 3000;
        fA = logspace(log10(10), log10(max(2*fs_local, 4*fc_local)), N_analog);
        OmegaA = 2*pi*fA;
        sA = 1j*OmegaA;

        H_target_analog = proto.Hfun(sA);

        % NBT-like remapped analog response
        u = sA;
        disc = gamma^2 - 4*(u.^2)*(Omega_o^2);
        x = (gamma + branchSign * sqrt(disc)) ./ (2*u);
        s_star = -2*Omega_o*Omega_c .* x ./ (x.^2 - Omega_o^2);
        H_nbt_analog = proto.Hfun(s_star);

        % ---- digital frequency grid ----
        N_digital = P.fitDenseN;
        w = linspace(1e-5, pi-1e-5, N_digital);
        z = exp(1j*w);
        fD = w * fs_local / (2*pi);

        % analog prototype plotted on digital axis for visual reference
        H_target_on_digital_axis = proto.Hfun(1j*2*pi*fD);

        % naive BLT
        s_blt = 2*fs_local * (1 - z.^(-1)) ./ (1 + z.^(-1));
        H_blt_naive = proto.Hfun(s_blt);

        % direct Möbius/NBT-like digital target
        disc_z = gamma^2 - 4*(s_blt.^2)*(Omega_o^2);
        x_z = (gamma + branchSign * sqrt(disc_z)) ./ (2*s_blt);
        s_star_z = -2*Omega_o*Omega_c .* x_z ./ (x_z.^2 - Omega_o^2);
        H_direct_target = proto.Hfun(s_star_z);

        % ---- fit a stable 4n-order digital IIR to direct target ----
        % frequency weighting: mild tilt toward high frequency
        wt = 0.35 + 0.65 * (w/pi).^1.5;

        try
            [b_hi, a_hi] = invfreqz(H_direct_target, w, hiOrder, hiOrder, wt, P.fitMaxIter, 1e-6);
        catch
            % fallback if MATLAB version prefers different signature
            [b_hi, a_hi] = invfreqz(H_direct_target, w, hiOrder, hiOrder, wt, P.fitMaxIter);
        end

        [b_hi, a_hi] = stabilize_tf(b_hi, a_hi);

        % normalize
        if a_hi(1) ~= 1
            b_hi = b_hi / a_hi(1);
            a_hi = a_hi / a_hi(1);
        end

        % ---- DC gain matching for fitted 4n-order model only ----
        H_target_dc = proto.Hfun(0);
        H_fit_dc = polyval(fliplr(b_hi), 1) / polyval(fliplr(a_hi), 1);
        
        if abs(H_fit_dc) > 1e-12
            g_hi = real(H_target_dc / H_fit_dc);
            b_hi = b_hi * g_hi;
        end

        H_fit_4n = freqz(b_hi, a_hi, w);

        % ---- IRKA reduction: 4n -> 2n ----
        [A,B,C,D] = tf2ss(b_hi, a_hi);

        % initial reduced model from balanced truncation if available,
        % otherwise simple stable diagonal initialization
        [Ar0, Br0, Cr0, Dr0] = initial_reduced_model(A,B,C,D,redOrder);

        [Ar, Br, Cr, Dr, irkaHist] = irka_discrete_siso(A,B,C,D,redOrder, ...
            P.irkaMaxIter, P.irkaTol, Ar0, Br0, Cr0, Dr0);

        [b_red, a_red] = ss2tf(Ar, Br, Cr, Dr, 1);
        b_red = real(b_red);
        a_red = real(a_red);

        [b_red, a_red] = stabilize_tf(b_red, a_red);

        if a_red(1) ~= 1
            b_red = b_red / a_red(1);
            a_red = a_red / a_red(1);
        end

        % ---- DC gain matching (IRKA gain correction) ----
        H_target_dc = proto.Hfun(0);
        H_red_dc = polyval(fliplr(b_red),1) / polyval(fliplr(a_red),1);
        
        if abs(H_red_dc) > 1e-12
            g = real(H_target_dc / H_red_dc);
            b_red = b_red * g;
        end

        H_irka_2n = freqz(b_red, a_red, w);

        % ---- magnitudes in dB ----
        mag_target_analog = 20*log10(max(abs(H_target_analog), 1e-12));
        mag_nbt_analog    = 20*log10(max(abs(H_nbt_analog), 1e-12));

        mag_proto_dig     = 20*log10(max(abs(H_target_on_digital_axis), 1e-12));
        mag_blt           = 20*log10(max(abs(H_blt_naive), 1e-12));
        mag_direct        = 20*log10(max(abs(H_direct_target), 1e-12));
        mag_fit_4n        = 20*log10(max(abs(H_fit_4n), 1e-12));
        mag_irka_2n       = 20*log10(max(abs(H_irka_2n), 1e-12));

        err_fit  = rms(mag_fit_4n  - mag_direct);
        err_irka = rms(mag_irka_2n - mag_direct);

        % ---- analog plot ----
        cla(ax1);
        semilogx(ax1, fA, mag_target_analog, 'LineWidth', 1.8); hold(ax1, 'on');
        semilogx(ax1, fA, mag_nbt_analog, '--', 'LineWidth', 1.8);
        grid(ax1, 'on');
        xlabel(ax1, 'Frequency (Hz)');
        ylabel(ax1, 'Magnitude (dB)');
        title(ax1, 'Analog-domain response');
        legend(ax1, {'Analog prototype', 'Analog after s \rightarrow s_*'}, ...
            'Location', 'southwest');
        xlim(ax1, [min(fA), max(fA)]);

        % ---- digital plot ----
        cla(ax2);
        semilogx(ax2, fD, mag_proto_dig, 'k', 'LineWidth', 1.6); hold(ax2, 'on');
        semilogx(ax2, fD, mag_blt, ':', 'LineWidth', 1.5);
        semilogx(ax2, fD, mag_direct, '--', 'LineWidth', 1.8);
        semilogx(ax2, fD, mag_fit_4n, '-.', 'LineWidth', 1.4);
        semilogx(ax2, fD, mag_irka_2n, 'LineWidth', 1.8);
        grid(ax2, 'on');
        xlabel(ax2, 'Frequency (Hz)');
        ylabel(ax2, 'Magnitude (dB)');
        title(ax2, sprintf('Digital-domain response (n=%d, 4n=%d, 2n=%d)', ...
            nAnalog, hiOrder, redOrder));
        legend(ax2, { ...
            'Analog prototype (reference)', ...
            'Naive BLT', ...
            'Direct M\ddot{o}bius target', ...
            sprintf('Fitted %d-order IIR', hiOrder), ...
            sprintf('IRKA reduced %d-order', redOrder)}, ...
            'Location', 'southwest');
        xlim(ax2, [20 24000]);
        ylim(ax2, [-40 20]);

        % ---- info text ----
        if isempty(irkaHist)
            irkaIter = 0;
            irkaDelta = NaN;
        else
            irkaIter = numel(irkaHist);
            irkaDelta = irkaHist(end).delta;
        end

        txt = sprintf([ ...
            'fs           = %.0f Hz\n' ...
            'fc           = %.2f Hz\n' ...
            'Q            = %.4f\n' ...
            'n (analog)   = %d\n' ...
            '4n fit order = %d\n' ...
            '2n IRKA ord. = %d\n\n' ...
            'Omega_o      = %.4e\n' ...
            'Omega_c      = %.4e\n' ...
            'gammaHat     = %.4f\n' ...
            'gamma        = %.4e\n' ...
            'branch       = %s\n\n' ...
            'Fit RMS err  = %.4f dB\n' ...
            'IRKA RMS err = %.4f dB\n' ...
            'IRKA iters   = %d\n' ...
            'IRKA delta   = %.3e\n\n' ...
            'Notes:\n' ...
            '- direct Möbius target is frequency-domain target\n' ...
            '- 4n model is stable invfreqz fit to that target\n' ...
            '- IRKA reduces 4n -> 2n in state-space\n'], ...
            fs_local, fc_local, Q_local, nAnalog, hiOrder, redOrder, ...
            Omega_o, Omega_c, gammaHat_local, gamma, ...
            ternary(branchSign < 0, 'lower (-)', 'upper (+)'), ...
            err_fit, err_irka, irkaIter, irkaDelta);

        set(infoBox, 'String', txt);
        drawnow;
    end
end

%% =========================================================
function proto = makePrototype(fc, Q)
% Prototype factory.
% You can replace this with other analog prototypes.
%
% The point of this wrapper is:
%   - proto.Hfun(s)  : direct evaluation
%   - proto.num/den  : known rational coefficients for order detection

    Omega0 = 2*pi*fc;

    proto.num = Omega0^2;
    proto.den = [1, Omega0/Q, Omega0^2];

    proto.Hfun = @(s) (Omega0^2) ./ (s.^2 + (Omega0/Q).*s + Omega0^2);
end

%% =========================================================
function [b, a] = stabilize_tf(b, a)
% Reflect unstable poles inside unit circle, rebuild denominator.
% Then roughly re-match numerator dc gain behavior.

    a = real(a);
    b = real(b);

    p = roots(a);
    for k = 1:numel(p)
        if abs(p(k)) >= 1
            p(k) = 1 / conj(p(k));
        end
    end
    a = real(poly(p));

    if a(1) ~= 1
        a = a / a(1);
    end

    % Keep zeros as-is, but stabilize if badly outside
    z = roots(b);
    for k = 1:numel(z)
        if abs(z(k)) > 1.5
            z(k) = 1 / conj(z(k));
        end
    end
    b = real(poly(z));

    % gain match at z=1 if possible
    num_dc = polyval(fliplr(b), 1);
    den_dc = polyval(fliplr(a), 1);
    if abs(num_dc) > 1e-12
        Hdc_old = polyval(fliplr(b), 1) / polyval(fliplr(a), 1);
        Hdc_new = b(1:end) * ones(numel(b),1) / (a(1:end) * ones(numel(a),1));
        if abs(Hdc_new) > 1e-12
            b = b * real(Hdc_old / Hdc_new);
        end
    end

    b = real(b);
    a = real(a);
end

%% =========================================================
function [Ar0, Br0, Cr0, Dr0] = initial_reduced_model(A,B,C,D,r)
% Try balanced truncation-based initialization if available;
% otherwise use a simple stable diagonal model.

    try
        sys = ss(A,B,C,D,1);
        sysr = balred(sys, r);
        [Ar0, Br0, Cr0, Dr0] = ssdata(sysr);
        return;
    catch
    end

    % fallback simple stable initialization
    ang = linspace(0.25, 1.1, ceil(r/2));
    rad = 0.7;
    p = rad * exp(1j*ang(:));
    p = [p; conj(p)];
    p = p(1:r);

    Ar0 = diag(realify_poles(p, r));
    Br0 = ones(r,1);
    Cr0 = ones(1,r);
    Dr0 = D;
end

%% =========================================================
function [Ar, Br, Cr, Dr, hist] = irka_discrete_siso(A,B,C,D,r,maxIter,tol,Ar,Br,Cr,Dr)
% Discrete-time IRKA for SISO
%
% H(z) = C (zI - A)^(-1) B + D
%
% This is a practical small-order implementation suitable for 8->4 etc.

    n = size(A,1);
    hist = struct('poles', {}, 'delta', {});

    prev_poles = sort_complex(eig(Ar));

    for k = 1:maxIter
        lam = eig(Ar);

        % Avoid division by very small poles
        lam(abs(lam) < 1e-8) = 0.1;

        % Discrete IRKA interpolation points
        sigma = 1 ./ lam;

        V = zeros(n, r);
        W = zeros(n, r);

        for i = 1:r
            V(:,i) = (sigma(i)*eye(n) - A) \ B;
            W(:,i) = (sigma(i)*eye(n) - A') \ C';
        end

        [V, W] = make_real_bases(V, W);
        V = V(:,1:r);
        W = W(:,1:r);

        M = W' * V;
        if rcond(M) < 1e-10
            M = M + 1e-8 * eye(size(M));
        end

        % biorthogonalize
        [L,U] = lu(M);
        V = V / U;
        W = W / L';

        Ar_new = W' * A * V;
        Br_new = W' * B;
        Cr_new = C * V;
        Dr_new = D;

        new_poles = sort_complex(eig(Ar_new));
        delta = norm(new_poles - prev_poles) / max(1, norm(prev_poles));

        hist(k).poles = new_poles;
        hist(k).delta = delta;

        Ar = Ar_new;
        Br = Br_new;
        Cr = Cr_new;
        Dr = Dr_new;

        if delta < tol
            break;
        end

        prev_poles = new_poles;
    end
end

%% =========================================================
function [Vreal, Wreal] = make_real_bases(V, W)
% Convert conjugate basis columns into real basis columns.

    tol = 1e-10;
    used = false(1, size(V,2));
    Vreal = [];
    Wreal = [];

    for i = 1:size(V,2)
        if used(i), continue; end

        vi = V(:,i);
        wi = W(:,i);

        if norm(imag(vi)) < tol
            Vreal = [Vreal, real(vi)];
            Wreal = [Wreal, real(wi)];
            used(i) = true;
            continue;
        end

        j = [];
        for jj = i+1:size(V,2)
            if ~used(jj) && norm(V(:,jj) - conj(vi)) < 1e-7 * max(1, norm(vi))
                j = jj;
                break;
            end
        end

        if ~isempty(j)
            Vreal = [Vreal, real(vi), imag(vi)];
            Wreal = [Wreal, real(wi), imag(wi)];
            used(i) = true;
            used(j) = true;
        else
            Vreal = [Vreal, real(vi)];
            Wreal = [Wreal, real(wi)];
            used(i) = true;
        end
    end
end

%% =========================================================
function p = realify_poles(p, r)
    p = p(:);
    out = [];
    used = false(size(p));

    for i = 1:numel(p)
        if used(i), continue; end
        if abs(imag(p(i))) < 1e-12
            out = [out; real(p(i))];
            used(i) = true;
        else
            out = [out; p(i); conj(p(i))];
            used(i) = true;
        end
    end

    if numel(out) < r
        out = [out; 0.6*ones(r-numel(out),1)];
    end
    p = out(1:r);
end

%% =========================================================
function x = sort_complex(x)
    x = x(:);
    [~, idx] = sortrows([real(x), imag(x)]);
    x = x(idx);
end

%% =========================================================
function out = ternary(cond, a, b)
    if cond
        out = a;
    else
        out = b;
    end
end